name = "Prismie Create"
author = "Lutitious"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd5a18e96677446bef1f838b56e3ae5169f6278da0c8205ff47f9faf8c81a903"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
unsup = "1.2.4"

[options]
acceptable-game-versions = ["1.21.1"]
