name = "Prismie Create"
author = "Lutitious"
version = "0.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10d37ec7e2368cc8841ae77ad2937983c212d55edfb2c02edf0757b84a73f04c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
unsup = "1.2.4"

[options]
acceptable-game-versions = ["1.21.1"]
