name = "Prismie Create"
author = "Lutitious"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "051abe1201791e93240899da9564e2546af9f6e8d7fbc35bdb29c2187e38597c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
unsup = "1.2.4"

[options]
acceptable-game-versions = ["1.21.1"]
